title: "Ideas for software features"
labels: ["enhancement"]
body:
  - type: "checkboxes"
    id: "no-duplicate-issues"
    attributes:
      label: "Please check that this feature hasn't been requested before"
      options:
        - required: True
          label: "I searched previous feature requests [here](https://github.com/pycross-org/matlab/issues?q=label%3Aenhancement+sort%3Acomments-desc) or [here](https://github.com/search?q=repo%3Apycross-org/matlab+label%3Aenhancement&type=issues) and didn't find any similar requests."
  - type: "textarea"
    id: "feature-description"
    validations:
      required: True
    attributes:
      label: "Feature description"
      description: "Please describe your requested feature"
  - type: "textarea"
    id: "possible-solution"
    attributes:
      label: "Possible implementation"
      description: "Please provide a few details as to how this feature might be implemented"
