name: "Bug report"
description: "Report a bug"
labels: ["bug"]
body:
  - type: "checkboxes"
    id: "no-duplicate-issues"
    attributes:
      label: "Please check that this bug hasn't been reported before"
      options:
        - required: True
          label: "I searched previous bug reports [here](https://github.com/pycross/matlab/issues?q=label%3Abug+sort%3Acomments-desc) or [here](https://github.com/search?q=repo%3Apycross/matlab+label%3Abug&type=issues) and didn't find any similar reports."
  - type: "checkboxes"
    id: "latest-version"
    attributes:
      label: "Please confirm that this bug affects the latest version"
      description: "Please verify the issue is present in the latest version by installing it with `pip install pyxmatlab==2024.03.02` and checking. If you have other issues or questions about earlier versions, please visit the [Q&A](https://github.com/pycross/matlab/discussions/new?category=q-a)."
      options:
        - required: True
          label: "This bug affects version `2024.03.02` of `pyxmatlab`."
  - type: "checkboxes"
    id: "operating-systems"
    attributes:
      label: "Please indicate which operating system(s) you are using"
      description: "You may select more than one"
      options:
        - label: "Linux"
        - label: "macOS"
        - label: "Windows"
  - type: "textarea"
    id: "expected"
    validations:
      required: True
    attributes:
      label: "Expected Behavior"
      description: "Please explain what **should** happen"
  - type: "textarea"
    id: "what-happened"
    attributes:
      label: "Current behaviour"
      description: "Please explain what happens instead of the expected behavior"
    validations:
      required: True
  - type: "textarea"
    id: "reproduce"
    validations:
      required: True
    attributes:
      label: "Steps to reproduce"
      description: "Please provide steps that would allow someone to reproduce the issue"
  - type: "textarea"
    id: "possible-solution"
    attributes:
      label: "Possible solution"
      description: "Please suggest a possible fix or any ideas you may have about the root cause"
