blank_issues_enabled: false
contact_links:
  - name: "Ask a question"
    url: "https://github.com/pycross-org/matlab/discussions/new?category=q-a"
    about: "Ask for help. Please search related Q&As in case your question has been asked before."
  - name: "Share an idea for a feature"
    url: "https://github.com/pycross-org/matlab/discussions/new?category=ideas"
    about: "Feature requests. Please search related ideas in case a similar request has been made before."
  - name: "Share an idea for documentation"
    url: "https://github.com/pycross-org/matlab/discussions/new?category=ideas-for-docs"
    about: "Suggestions for documentation or tutorial content. Please search related ideas in case a similar request has been made before."
  - name: "Share an idea for project infrastructure"
    url: "https://github.com/pycross-org/matlab/discussions/new?category=ideas-for-infrastructure"
    about: "Suggestions for project infrastructure and tooling. Please search related ideas in case a similar request has been made before."
