name: "⚠️ Internal issue"
description: "Please only select this if you are a maintainer or have been directed to do so."
labels: ["internal"]
body:
  - type: "checkboxes"
    id: "usage"
    attributes:
      label: "Please use this form appropriately."
      options:
        - required: True
          label: "I am a maintainer has directed me to use this form."
  - type: "textarea"
    id: "description"
    validations:
      required: True
    attributes:
      label: "Description"
      description: "Please describe the change."
  - type: "textarea"
    id: "possible-solution"
    attributes:
      label: "Steps"
      description: "Please describe the steps to making this change."
